
title: My Resume
url: 'http://slayerjain.surge.sh'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Shubham Jain
tagline: Cloud architect, musician and Deep learning enthusiast. 
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: shubhamkjain@outlook.com
phone: +91-8882110959
website: slayerjain.surge.sh #do not add http://
linkedin: slayerjain
github: slayerjain
twitter: slayerjain


# Tracker
analytics: UA-73290805-1
#Update all the sections by editing the files inside _includes folder.
